### ISSUE TITLE
标点符号模型预测报错

### ISSUE THREAD

**Issue by account15222** [yeyupiaoling/PunctuationModel#19]
大佬 这是什么情况导致的呢 我训练蒙古文标点符号呢 预测的时候也用蒙古文文本
[2024-08-15 14:20:05,522] [    INFO] - Already cached /root/.paddlenlp/models/ernie-3.0-medium-zh/ernie_3.0_medium_zh_vocab.txt
[2024-08-15 14:20:05,550] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/ernie-3.0-medium-zh/tokenizer_config.json
[2024-08-15 14:20:05,551] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/ernie-3.0-medium-zh/special_tokens_map.json
[2024-08-15 14:20:07.638259 INFO   ] predictor:__init__:60 - 标点符号模型加载成功。
Traceback (most recent call last):
  File "infer.py", line 17, in <module>
    result = pun_executor(args.text)
  File "/data/Speech/PunctuationModel/utils/predictor.py", line 108, in __call__
    input_ids, seg_ids, seq_len = self.preprocess(text)
TypeError: cannot unpack non-iterable NoneType object

**Comment by yeyupiaoling** [comment]
@account15222 这个模型只支持中文
